sudo: false
dist: xenial
language: python
cache: pip
python:
  - 3.7.1
install:
  - pip3 install codecov
  - pip3 install codacy-coverage
  - pip3 install -e .
script:
  - pytest -v --cov=./
after_success:
  - codecov -t $CODECOV_PROJECT_TOKEN
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: mortele
  password: $PYPI_PASSWORD
  on:
    tags: true
